### ISSUE TITLE
Message on app launch

### ISSUE THREAD

**Issue by iulianpn** [bgallois/OpenJournal#7]
Hello,

I have this message each time I start the app.

<img width="249" alt="message_startup_openjournal" src="https://github.com/bgallois/OpenJournal/assets/133751574/d699d8d9-9e70-4b97-b7f2-8fd99db14e04">

I must delete him and after everything is OK.

How can I fix this pb ?

Thx - iulian

**Comment by bgallois** [comment]
The lock file should be deleted when OpenJournal is closed. Did you close the program properly, or did you let the system takes care of the closing at shutdown?

**Comment by iulianpn** [comment]
Even if I close the progrem properly I have the same message.
My conf : windows 11 Pro with latest upgrades.

**Comment by bgallois** [comment]
I'am unable to to reproduce this error on Windows.
Are you sure the program is closed using the system tray?
![image](https://github.com/bgallois/OpenJournal/assets/23381534/329a567f-6d6b-4e7e-8e0c-10b83f465775)

I will release a new version of OpenJournal today with all the packages up-to-date to see if it solve the problem.

**Comment by iulianpn** [comment]
Oops, sorry
I think I misunderstood the problem:
1. When I close the application using the system tray, I can reopen it without problems, everything is OK
2. The problem appears when I don't close the application (app running in system tray) and restart the system. I try to open it and now I have the message.

**Comment by bgallois** [comment]
I seem to me that it's more a problem related to Qt and Windows integration. I released version [1.3.3](https://github.com/bgallois/OpenJournal/releases/tag/v1.3.3) with newer version of all the packages to see if it's fix the problem.
If the problem persists, I will change the behavior of OpenJournal with a simple warning message that do not forbid the program opening.

**Comment by iulianpn** [comment]
Tested with latest version 1.3.3 : same message.
<img width="249" alt="openjournal_1 3 3_startup_message" src="https://github.com/bgallois/OpenJournal/assets/133751574/90601c4e-1ab3-4fa9-aee8-ea23423e7f6e">

**Comment by bgallois** [comment]
Should be fixed with 749cfb64259f08115593cb964c9aaac5190b2a3f released in [1.3.4](https://github.com/bgallois/OpenJournal/releases/tag/v1.3.4).

**Comment by iulianpn** [comment]
I confirm, in my case everything it's OK even after reboot.
Thx for quickly debugging.
